feat: 아주아주 간단한 장바구니 생성 추가
nhnacademy-be7-nuri-books/nuri-books-book pull request #188
Opened 2024-10-31 00:34 UTC by Jprotection

2024-10-31 02:16 UTC, hxcva1 reviewed
고생하셨습니다!

2024-10-31 02:16 UTC, hxcva1 commented on src/main/java/shop/nuribooks/books/member/cart/controller/CartController.java
> +	public ResponseEntity<CartAddResponse> addToCart(@PathVariable Long memberId, @PathVariable Long bookId) {
아마 도서 수량이 같이 들어올 것으로 예상해서 따로 body로 받는 부분이 있어야 할 것으로 예상됩니다 👍

2024-10-31 07:07 UTC, kkyongg approved these changes
수고하셨습니다!

2024-10-31 07:07 UTC, kkyongg commented on src/main/java/shop/nuribooks/books/member/cart/controller/CartController.java
> +	public ResponseEntity<CartAddResponse> addToCart(@PathVariable Long memberId, @PathVariable Long bookId) {
@valid 유효성 검사는 따로 하지 않아도 될까요?

2024-10-31 08:00 UTC, Jprotection commented on src/main/java/shop/nuribooks/books/member/cart/controller/CartController.java
> +	public ResponseEntity<CartAddResponse> addToCart(@PathVariable Long memberId, @PathVariable Long bookId) {
수정하겠습니다.

2024-10-31 08:03 UTC, Jprotection commented on src/main/java/shop/nuribooks/books/member/cart/controller/CartController.java
> +	public ResponseEntity<CartAddResponse> addToCart(@PathVariable Long memberId, @PathVariable Long bookId) {
pathVariable로 들어온 회원 id에 해당하는 회원이 없거나, 도서 id에 해당하는 도서가 없다면 service 계층에서 NotFound예외를 던지기 때문에 controller에서는 유효성 검사를 하지 않아도 될 것 같습니다.

2024-11-04 12:42 UTC, rjsdn0124 requested changes
테스트 한 번만 더 확인해주세요!

2024-11-05 02:08 UTC, rjsdn0124 approved these changes

2024-11-05 02:09 UTC, merged