Refactor/category
nhnacademy-be7-nuri-books/nuri-books-book pull request #198
Opened 2024-11-03 18:33 UTC by Jkim052

아우 일단 죄송합니다.
브레드크럼을 적용하기 위해서 카테고리에 path 를 추가했습니다.
이에 맞춰서 카테고리 dto 수정했습니다.
ResponseMessage 가 record 가 아니라 못참고 수정했습니다.
컨트롤러의 응답 수정했습니다.
카테고리 테스트가 응답값과 바뀐 dto 에 맞춰서 수정되었습니다.
Querydsl 적용을 위해 pom.xml 수정
Repository test 에 @Import(QuerydslConfiguration.class) 어노테이션이 없으면 test가 터져서 전체 추가했습니다.

2024-11-05 00:59 UTC, rjsdn0124 commented
테스트 커버리지 올려주세요!

2024-11-05 04:59 UTC, hxcva1 reviewed
고생 많으셨습니다! 👍

2024-11-05 04:59 UTC, hxcva1 commented on src/main/java/shop/nuribooks/books/book/category/service/impl/CategoryServiceImpl.java
> -		boolean isDuplicate = categoryRepository.existsByNameAndParentCategoryIsNull(dto.name());
💭 dto 보다는 명확하게 categoryRequest로 하면 어떨까요

2024-11-05 04:59 UTC, hxcva1 commented on src/main/java/shop/nuribooks/books/book/category/service/impl/CategoryServiceImpl.java
> -
💭 setter보다는 의도가 명확하게 따로 메서드를 두는건 어떨까요?

2024-11-05 13:25 UTC, Jkim052 commented on src/main/java/shop/nuribooks/books/book/category/service/impl/CategoryServiceImpl.java
> -		boolean isDuplicate = categoryRepository.existsByNameAndParentCategoryIsNull(dto.name());
수정했습니다~

2024-11-06 20:57 UTC, b1ueday approved these changes
고생하셨습니다 👍

2024-11-06 21:24 UTC, b1ueday requested changes
.

2024-11-06 21:55 UTC, hxcva1 approved these changes
고생하셨습니다! 👍

2024-11-07 08:41 UTC, closed without merging