Feature/order information 주문 폼 불러오기 기능 추가
nhnacademy-be7-nuri-books/nuri-books-book pull request #261
Opened 2024-11-13 12:55 UTC by yeon-so

## 구현 내용

- [x] 비회원
  - 독서 정보
  - 나머지의 값 null
- [x] 회원
  - 사용자 정보
  - 주소 정보
  - 도서 정보

- 특이사항
  - AddressResponse 의 경우만 주소 파트에서 사용하는 응답 dto를 그대로 사용

2024-11-13 13:01 UTC, itaekit approved these changes
저는 코드가 아닌 사람을 보고 승인합니다.

2024-11-13 16:29 UTC, rjsdn0124 requested changes
복잡한 기능 잘 구현하신 것 같습니다! 고생하셨습니다!
리뷰 확인 부탁드립니다!

2024-11-13 16:29 UTC, rjsdn0124 commented on src/main/resources/application.yml
> +    prefer-ip-address: true
이 수정은 어떤 역할인지 궁금합니다.

2024-11-13 16:29 UTC, rjsdn0124 commented on src/main/java/shop/nuribooks/books/order/order/dto/OrderInformationResponse.java
> +	// todo: 잔여 포인트
멤버의 field에 포인트가 저장되어 있습니다!

2024-11-13 16:29 UTC, rjsdn0124 commented on src/main/java/shop/nuribooks/books/order/order/controller/OrderController.java
> +		OrderInformationResponse result = userId
Optional의 map을 이용하여 member와 customer의 처리를 다르게 한 점이 인상깊습니다.
하지만 Optional 내장 함수 중, Optional.ifPresentOrElse 함수를 사용해보는 건 어떨까요?
있을 때 없을 때 2가지 상황의 람다 함수를 인자로 전달할 수 있습니다!

2024-11-13 16:29 UTC, rjsdn0124 commented on src/main/java/shop/nuribooks/books/order/order/service/OrderServiceImpl.java
> +		// 도서 기여자 정보 가져오기
혹시 기여자 정보가 필요한 이유가 있을까요?

2024-11-13 16:29 UTC, rjsdn0124 commented on src/main/java/shop/nuribooks/books/order/order/service/OrderServiceImpl.java
> +	@Override
바로 주문과 장바구니 주문을 하나로 통합할 수는 없을까요?

2024-11-13 16:30 UTC, rjsdn0124 approved these changes

2024-11-13 22:25 UTC, yeon-so commented on src/main/resources/application.yml
> +    prefer-ip-address: true
유레카에서 정보를 등록할 때 도메인으로 등록할 지 IP로 등록할 지 확인하는 용도인데 제 PC에서는 도메인 등록 시 통신 에러기 납니다. 혹시 이후에 문제 발생 시 복구 하겠습니다.

2024-11-13 22:44 UTC, yeon-so commented on src/main/java/shop/nuribooks/books/order/order/dto/OrderInformationResponse.java
> +	// todo: 잔여 포인트
넵! 해당 부분은 반영하겠습니다.

2024-11-14 04:47 UTC, yeon-so commented on src/main/java/shop/nuribooks/books/order/order/controller/OrderController.java
> +		OrderInformationResponse result = userId
Optional.ifPresentOrElse 가 있었군요! 참고하겠습니다.

2024-11-14 04:47 UTC, yeon-so commented on src/main/java/shop/nuribooks/books/order/order/service/OrderServiceImpl.java
> +		// 도서 기여자 정보 가져오기
주문 폼에서 기여자(작가) 정보가 나오는 경우가 있어서 우선 가져오도록 처리하였으나 이 부분은 의견을 물어보고 다시 반영하겠습니다.

2024-11-14 04:48 UTC, yeon-so commented on src/main/java/shop/nuribooks/books/order/order/service/OrderServiceImpl.java
> +	@Override
장바구니를 통한 주문과 바로 주문이 필요한 매개변수가 달라 우선은 따로 처리하겠습니다. 장바구니가 완전히 구현되었을 시 이 부분을 반영할 수 있다면 반영해보겠습니다.

2024-11-14 04:55 UTC, merged